### ISSUE TITLE
invalid format?

### ISSUE THREAD

**Issue by nottooloud** [ObjectIsAdvantag/postman-xapi#2]
1 invalid import format(s)
Postman Collection Format v1 is no longer supported and can not be imported directly. You may convert your collection to Format v2
 and try importing again.
NAME
FORMAT
IMPORT AS
xAPI (as Admin)
Postman Collection v1
Collection

**Comment by ObjectIsAdvantag** [comment]
thanks @nottooloud, just updated the collection, 
hope this fixes your issue, 
closing for now, feel free to reopen if needed
